### ISSUE TITLE
Provided demo files

### ISSUE THREAD

**Issue by tdiep213** [tdiep213/552Project#13]
Looks like they provided shell files for us to use in each of the demos.
Fetch, Decode, Execute, Memory, Writeback, and a main proc file. Nothing too surprising, but looks like we'll have to instantiate our modules in those files at some point.

**Comment by hmkiff** [comment]
Sounds good. I just did a lot of control work so if I don't get to it tonight, I will get to it tomorrow alongside the memory implementation.

**Comment by tdiep213** [comment]
Sounds good, no rush. We've got most of the processor done. I don't want to jinx it but I think there's a good chance we'll be done before the weekend!
