### ISSUE TITLE
Zero extension input determination

### ISSUE THREAD

**Issue by hmkiff** [tdiep213/552Project#8]
The extension unit makes sense, especially after you explained it the other night. One problem I am running into is how the input to the extender is decided. In order to Zero-Ext when need to pass only 5, 8, or 10-bit immediates to the module, so we end up having to choose the size which will require another mux/case statement anyway. We can either handle that logic in main, or we can handle it within the module (which may be easier). The biggest thing this would change would be making ImmSel 3 bits instead of 2 if we keep everything together. Lmk what you think and if you want me to handle it or if you are taking it :D !

**Comment by tdiep213** [comment]
Yeah, looks like we'll need a mux to pick between the 3, but we shouldn't need it in the bit-extend module

**Comment by hmkiff** [comment]
Sounds good. I'll add something to either main or control when I hop on next
